// src/components/shared/media-card/media-card.component.ts

import { Component, ChangeDetectionStrategy, input, AfterViewChecked } from '@angular/core';
import { CommonModule, NgOptimizedImage } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Media } from '../../../models/media.model';

declare var lucide: any;

@Component({
  selector: 'app-media-card',
  standalone: true,
  imports: [CommonModule, NgOptimizedImage, RouterLink],
  templateUrl: './media-card.component.html',
  styleUrls: ['./media-card.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MediaCardComponent implements AfterViewChecked {
  media = input.required<Media>();

  ngAfterViewChecked() {
    lucide.createIcons();
  }
}

@if(media(); as mediaItem) {
<a [routerLink]="['/media', mediaItem.type, mediaItem.id]" class="media-card-link group block">
  <div class="media-card relative aspect-[2/3] overflow-hidden rounded-lg">
    <img [ngSrc]="mediaItem.poster" [alt]="mediaItem.title" fill class="media-card-poster object-cover transition-transform duration-300 ease-in-out group-hover:scale-110 group-hover:blur-sm">
    <div class="media-card-overlay absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
      <div class="play-button w-20 h-20 bg-black/50 backdrop-blur-sm border border-white/20 rounded-full flex items-center justify-center">
        <i data-lucide="play" class="w-10 h-10 text-white ml-1"></i> </div>
    </div>
  </div>
  <div class="mt-2">
    <h3 class="font-semibold text-white truncate group-hover:text-primary transition-colors">{{ mediaItem.title }}</h3>
    <p class="text-xs text-text-dim">{{ mediaItem.year }}</p>
  </div>
</a>
}

// components/MediaCard.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { MediaItem } from '../types';

interface MediaCardProps {
    item: MediaItem;
}

const MediaCard: React.FC<MediaCardProps> = ({ item }) => {
    return (
        <Link to={`/media/${item.type}/${item.id}${item.resumeLink || ''}`} className="block group" data-tv-focusable>
            <div className="relative aspect-[2/3] bg-gray-800 rounded-lg overflow-hidden">
                <img 
                    loading="lazy" 
                    src={item.poster} 
                    alt={item.title} 
                    className="w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-110 group-hover:blur-sm" 
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                    {/* AQUI: Ajustado para w-24 h-24 para ser maior */}
                    <div className="w-24 h-24 transform transition-transform duration-300 group-hover:scale-110">
                        <img src="https://i.ibb.co/Q7V0pybV/bot-o-play-sem-bg.png" alt="Play" className="w-full h-full object-contain" />
                    </div>
                </div>
                 <img src="https://i.ibb.co/PGJ87dN5/cineveo-logo-r.png" alt="CineVEO Logo" className="absolute bottom-2 right-2 w-auto h-4 opacity-60 z-10 hidden md:block" />
            </div>
            <h3 className="font-semibold text-white/90 truncate mt-2 text-sm md:text-base group-hover:text-yellow-400 transition-colors">{item.title}</h3>
            <p className="text-xs text-gray-400 hidden md:block">{item.year}</p>
        </Link>
    );
};

export default MediaCard;
